version: '3'

services:
  mysql:
    image: staff0rd/mysql-minimal
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    networks:
      - discordbotnetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  java-app:
    image: quay.io/akalenyu/polytalker:aug9
    container_name: discordbot-container
    environment:
      - TOKEN=${TOKEN}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env
    networks:
      - discordbotnetwork
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logfile.log
networks:
  discordbotnetwork:
