version: '3'

services:
  mysql:
    image: staff0rd/mysql-minimal
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - discordbotnetwork
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discordbot-container
    environment:
      - TOKEN=${TOKEN}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - discordbotnetwork
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logfile.log
networks:
  discordbotnetwork:
